# see https://docs.travis-ci.com/user/languages/python/
language: python
# python versions to be tested
python:
#  - "2.7" # see https://github.com/WolfgangFahl/gremlin-python-tutorial/issues/7
  - "3.7"
# allow gui output
services:
  - xvfb
# command to install dependencies
install:
  - pip install -r src/requirements.txt
# command to run tests
script:
  - pytest
