site_name: play-chess-with-a-webcam API Documentation
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - import os
            - sys.path.insert(0, os.path.abspath("."))
          selection:
            docstring_style: google
          rendering:
            show_source: true
nav:
  - API: index.md
