#!/bin/bash
# workaround issue with PYTHONPATH for 2.7 still being active
echo $PYTHONPATH | grep 2.7 > /dev/null
if [ $? -eq 0 ]
then
  export PYTHONPATH=""
fi
scriptdir=$(dirname $0)
python=python3
if [ "$USER" = "travis" ]
then
  pytest
else
  $python -m pytest --cov=./ .
fi
